# Image for use in this project

image: ubuntu

# Commands for the build process

install:
  # Install node via NVM
  - nvm --version
  - nvm install 10.14.1
  - nvm use 10.14.1
  - yarn install

test_script:
  - yarn test

# Turn the build off, as otherwise it will try to build a .net project

build: off
